language: java
jdk: oraclejdk8
install: true

cache:
  directories:
  - $HOME/.gradle
  - $HOME/.m2

before_install:
  - ./scripts/npm-settings.sh
  - ./scripts/ci-gradle-env.sh

before_deploy:
  - export PATH=$PATH:$HOME/.local/bin

script:
  - ./gradlew build

deploy:
  - provider: script
    skip_cleanup: true
    script: ./gradlew artifactoryPublish
    on:
      branch: master

  - provider: script
    skip_cleanup: true
    script: ./gradlew artifactoryPublish
    on:
      tags: true
