name: Java
on:
  workflow_call:
    secrets:
      ARTIFACTORY_USERNAME:
        required: true
      ARTIFACTORY_PASSWORD:
        required: true
      RELEASES_REPO:
        required: true
      SNAPSHOTS_REPO:
        required: true
      CONTEXT_REPO_ROOT:
        required: true
      FORGEROCK_MAVEN_USERNAME:
        required: true
      FORGEROCK_MAVEN_PASSWORD:
        required: true
jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    env:
      FORGEROCK_MAVEN_USERNAME: ${{ secrets.FORGEROCK_MAVEN_USERNAME }}
      FORGEROCK_MAVEN_PASSWORD: ${{ secrets.FORGEROCK_MAVEN_PASSWORD }}
      ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
      ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
      CONTEXT_REPO_ROOT: ${{ secrets.CONTEXT_REPO_ROOT }}
      SNAPSHOTS_REPO: ${{ secrets.SNAPSHOTS_REPO }}
      RELEASES_REPO: ${{ secrets.RELEASES_REPO }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
        cache: 'gradle'
    - run: ./scripts/ci-gradle-env.sh
    - run: ./scripts/npm-settings.sh
      env:
        ARTIFACTORY_EMAIL: not-real-no-bounty@example.com
    - uses: gradle/gradle-build-action@v2
      with:
        arguments: build
